### ISSUE TITLE
Moderate stored events

### ISSUE THREAD

**Issue by 0xtrr** [hoytech/strfry#118]
Hi!

Would it be possible to add some kind of way to delete specific events from the relay db? Or even any event belonging to a pubkey?

The reason I ask this is that as a public relay operator, sometimes people misuse the relay to post CSAM, scams, or simply other stuff I don't want on the relay. Therefore, it would be great if I could somehow remove their content from my relay DB. I do run my own write policy plugin but it's impossible to stop everything I don't want on my relay at event ingestion.

**Comment by hoytech** [comment]
Hi! This is possible with the `strfry delete` command, although the interface isn't necessarily ideal. You pass it arbitrary nostr filters, so you can delete individual events like this:

    strfry delete --filter='{"ids":["7df5389a099e7f20b5557d97efd1d4c04e84846d6444019cf94f10075cef7152"]}'

And all the events from a particular pubkey like this:

    strfry delete --filter='{"authors":["4fecd36ea23ba215c56ec3a5f26b4eed8e01c8d2c5a4700d2222393677f2d39f"]}'

(values above just randomly selected from a prod data-set -- sorry to whoever they belong to)

**Comment by 0xtrr** [comment]
Oh man, how did I not know about this.. Thanks Doug!
