### ISSUE TITLE
exporting issues 

### ISSUE THREAD

**Issue by Darecjo** [hoytech/strfry#122]
i have a `data.mdb` of `24.3GB` in size i want to export it to use the newest strfry version however it seems that exporting does not working. Any solutions for this ?

**Comment by hoytech** [comment]
What error are you seeing? You can't use strfry `1.0.0+` to export a v2 DB. The recommended way is to use `0.9.7` and export with `--fried`, then upgrade to `1.0.0+` and import with `--fried`.

It will take longer, but you should be able to export and import using any version if you don't use `--fried`.

**Comment by Darecjo** [comment]
i tried to use —fried but the argument does not exist i’m using an old version of strfry i dont think it has fried however before it was exporting normally but now it does not. I will send technical details later on 🙏

**Comment by hoytech** [comment]
Yeah, `--fried` export support was added to `0.9.7` so you have to upgrade to this, `export --fried`, then upgrade again to `1.0.0+` and the `import --fried`.

**Comment by Darecjo** [comment]
is there any docs on how to upgrade it?

**Comment by hoytech** [comment]
A little bit here: https://github.com/hoytech/strfry/?tab=readme-ov-file#compile

Basically, do this:

    git fetch
    git checkout 0.9.7
    make update-submodules
    make clean && make -j4

After that you have a `0.9.7` `strfry` binary. Do the `export --fried`. Then, do the same as above but use version `1.0.1` instead. Then do the `import --fried`.

Yeah I know it's a bit annoying, sorry!

**Comment by Darecjo** [comment]
Sorry for the late reply hoytech thanks for the help I will see what I can do 🙏

**Comment by Darecjo** [comment]
I did exactly the same with an addition step concerning stashing the `strfry.conf` and I still have the same error.
![image](https://github.com/user-attachments/assets/38cfcac3-0d9d-4795-921f-52f21867d9ae)

**Comment by raucao** [comment]
It's `strfry export`, not just `export`.

**Comment by Darecjo** [comment]
I’ll check it out and let you know thanks again 🙏

**Comment by hoytech** [comment]
Also, that version of strfry does not support `--fried`, so you should either upgrade to 0.9.7 or just do it without `--fried` (the import will take longer, but it will still work)

**Comment by Darecjo** [comment]
I used the export without the fried argument it's working fine, thanks again.
