### ISSUE TITLE
Docker builds seem to be missing nodejs, required for js plugins.

### ISSUE THREAD

**Issue by jackedproxy** [hoytech/strfry#128]
Greetings, 
I looked through the existing issues as well as the Telegram group, but couldn't find the issue I'm currently running into.

Unsure if I just did something wrong or if this is by-design, but the docker images that are built from the docker files are missing nodejs, which is required for plugins. I can confirm I had the same issue for both the Arch and the Alpine builds. 
![image](https://github.com/user-attachments/assets/7b545983-f686-4260-a322-639351501264)

When attempting to execute a plugin script, node would not be found. 
It was not in the PATH, but I also couldn't find it anywhere within the container (used find / --name node and which node).
![image](https://github.com/user-attachments/assets/0002683a-4f18-41f7-97d9-df3eb1ede9d1)

I am using the Arch build, so I worked around this by having pacman install nodejs at the time of the build.
![image](https://github.com/user-attachments/assets/945decde-8648-4a27-88e4-0a5428d63e0b)

If I missed something, or plugins aren't expected to be supported when running on docker containers, please let me know.

**Comment by raucao** [comment]
Node.js is not required for plugins per se. If a plugin you want to use is based on node.js, then you will have to set up strfry in such a way that node.js is available in that environment, like you did with your custom Docker image there.

**Comment by jackedproxy** [comment]
Ah I see, that makes sense given strfry seems to be (mostly?) agnostic to the language that plugins use.
I see the issue now, thanks.
Will close.
