### ISSUE TITLE
Whitelist / Blacklist pubkeys

### ISSUE THREAD

**Issue by pjv** [hoytech/strfry#15]
Is there, or could there be, a way to configure strfry for whitelisting or blacklisting pubkeys allowing or disallowing posting to the instance?

**Comment by hoytech** [comment]
Currently there is not, but there should be, and I am working on it! I will update this ticket ASAP when this is ready.

**Comment by jb55** [comment]
I want to build a paid damus relay and I would like to use strfry. would love if this was a thing! and a way to dynamically add users so I can create a payment interface.

**Comment by hoytech** [comment]
Nice! We're working on plugin system that will allow this. It's currently in the `beta` branch and a few people are testing it out, but probably not ready for serious production yet.

Here are the docs for plugins including an example of a whitelist:

https://github.com/hoytech/strfry/blob/beta/docs/plugins.md

**Comment by pjv** [comment]
Thanks @hoytech

 let’s say I’m running strfry via docker-compose. Should bind mounting that plugin to the same path (/etc) as strfry.conf work?

**Comment by hoytech** [comment]
Hmm good question. I think that should probably work, as long as the container has all the dependencies it needs to execute the plugin script. For example, if your plugin is in node, you'll need the `node` binary and all npm modules you use to exist inside the container.

**Comment by pjv** [comment]
I’ll probably re-write it in python. Since the Dockerfile in this repo looks to be stock ubuntu, I assume it will have python3. Maybe I’ll put the plugin in /app instead of having an executable sitting in /etc which is kinda bad form.

**Comment by hoytech** [comment]
Makes sense. Yep I assume it will have a system python available so it should "just work". Let me know if not though!

**Comment by pjv** [comment]
@hoytech in fact, not. I guess the `ubuntu:jammy` docker image is pretty stripped down (which makes sense). I had to modify the `Dockerfile` like so:

<img width="658" alt="SCR-20230212-be7" src="https://user-images.githubusercontent.com/327716/218316178-c69a8e8d-80e2-4b68-a8f5-1b42b94e747a.png">

I have a lightly tested and seemingly working python adaptation of your `whitelist.js` example. After I get it tested better, maybe I’ll put it in a gist along with the modified Dockerfile and relevant strfry config to make it work under docker as I am running it.

**Comment by pjv** [comment]
Now running the beta [decc3ae] live as my semi-private relay with just a few hand-picked pubkeys allowed to post. The whitelist is rejecting lots of spam. So far, so good.

**Comment by hoytech** [comment]
Glad to hear it's working -- thanks for letting us know. A gist of instructions we can link to would be great!

**Comment by pjv** [comment]
@hoytech Took me a while to work out all the kinks, but [here’s my repo](https://github.com/pjv/strfry_personal_docker) that implements a docker-based personal relay server with strfry using the write policy plugin I developed. This may currently be the fastest, easiest way to get a nostr relay up and running.

**Comment by Giszmo** [comment]
Is this issue up to date? docs/plugins.md is on master and https://gitlab.com/soapbox-pub/strfry-policies/ makes good use of it. With the latter, black- and white lists are easy to do.
