### ISSUE TITLE
Core dump when run multiple in stream mode

### ISSUE THREAD

**Issue by etemiz** [hoytech/strfry#4]
I am collecting events from relays by running multiple instances of strfry in stream mode and this happens like in every few hours.

terminate called after throwing an instance of 'std::runtime_error'
  what():  duplicate insert into Event

Loguru caught a signal: SIGABRT
Stack trace:
13      0x7f3c179f0a00 /lib/x86_64-linux-gnu/libc.so.6(+0x126a00) [0x7f3c179f0a00]
12      0x7f3c1795eb43 /lib/x86_64-linux-gnu/libc.so.6(+0x94b43) [0x7f3c1795eb43]
11      0x7f3c17cd52b3 /lib/x86_64-linux-gnu/libstdc++.so.6(+0xdc2b3) [0x7f3c17cd52b3]
10      0x5639ff8e37c3 ./strfry(+0x2b97c3) [0x5639ff8e37c3]
9       0x5639ff8e3110 ./strfry(+0x2b9110) [0x5639ff8e3110]
8       0x5639ff64d76d ./strfry(+0x2376d) [0x5639ff64d76d]
7       0x7f3c17ca7518 /lib/x86_64-linux-gnu/libstdc++.so.6(+0xae518) [0x7f3c17ca7518]
6       0x7f3c17ca72b7 /lib/x86_64-linux-gnu/libstdc++.so.6(+0xae2b7) [0x7f3c17ca72b7]
5       0x7f3c17ca724c /lib/x86_64-linux-gnu/libstdc++.so.6(+0xae24c) [0x7f3c17ca724c]
4       0x7f3c17c9bbbe /lib/x86_64-linux-gnu/libstdc++.so.6(+0xa2bbe) [0x7f3c17c9bbbe]
3       0x7f3c178f27f3 abort + 211
2       0x7f3c1790c476 raise + 22
1       0x7f3c17960a7c pthread_kill + 300
0       0x7f3c1790c520 /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f3c1790c520]
2023-01-11 08:15:48.106 (2499.091s) [Writer          ]FATL| Signal: SIGABRT
Aborted (core dumped)

**Comment by hoytech** [comment]
Wow, thanks for your early testing! I'm looking into this now.
