### ISSUE TITLE
g++: fatal error: Killed signal terminated program cc1plus

### ISSUE THREAD

**Issue by satoshisound** [hoytech/strfry#41]
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make: *** [golpe/rules.mk:28: build/config.o] Error 1
make: *** Waiting for unfinished jobs....

Trying to install on an Ubuntu 22. This occurs when running `make -j4`

I ran `sudo apt update` and `sudo apt upgrade` followed by the commands in the docs. Any ideas?

**Comment by satoshisound** [comment]
I was trying with a 4gb Digital Ocean droplet. I resized to 8gb and it worked.

**Comment by hoytech** [comment]
Yep as you figured out, it's probably g++ running out of memory. If you do `make -j4` then that will actually run 4 processes in parallel. If you want to compile on machines with less memory, you could also try just `make`.
