### ISSUE TITLE
Using a Reverse Proxy like e.g. NGINX

### ISSUE THREAD

**Issue by theAkito** [hoytech/strfry#53]
The [README mentions](https://github.com/hoytech/strfry#running-a-relay), there'll be details soon, on how the NGINX configuration should look like. However, https://github.com/hoytech/strfry/issues/50 makes me wonder, whether there need to be some special settings enabled, to make this fully work.

Can I use a 101 NGINX Proxy configuration, as is used by most services?
How can I make sure, i.e. test, the service works fine & all functionalities are working?

I suggest the README gets a sections about NGINX.

**Comment by hoytech** [comment]
Hi! There is a community-contributed example nginx config here:

https://github.com/hoytech/strfry/blob/master/docs/DEPLOYMENT.md#sample-nginx-starter-config

It may need a small amount of tweaking, but it should be pretty close, depending on if you have special requirements. Let us know if you hit any issues!

**Comment by theAkito** [comment]
@hoytech

Thank you for the information. 🙂

I set this up, triple checked & the Let's Encrypt provided by my NGINX instance worked flawlessly. All works regarding NGINX.

Now, when I try to reach the service, I get a Bad Gateway response. Triple checked the port etc. in the NGINX configuration is fine.

Then, I `curl`ed the service itself & getting the following error.

```
curl: (56) Recv failure: Connection reset by peer
```

Apparently, something's wrong with the service. Not sure what. Didn't really change anything in `strfry.conf`, either, except the server info.

**Comment by theAkito** [comment]
This NGINX configuration example was enough for me. Would be wise to extend it for other, less experienced, users, at some point, though. 😄
