### ISSUE TITLE
Compilation Errors

### ISSUE THREAD

**Issue by leesalminen** [hoytech/strfry#61]
I'm trying to compile & run strfry and when running make I receive an error message of:

```
ubuntu@x11r0n:~/strfry$ make -j4
perl golpe/gen-fbs.pl
perl golpe/gen-config.pl
golpe/external/rasgueadb/rasgueadb-generate golpe.yaml build
perl golpe/gen-main.cpp.pl
error: /home/ubuntu/strfry/fbs/nostr-index.fbs:4: 16: error: expecting: ] instead got: :
flatc failure building fbs/nostr-index.fbs at golpe/gen-fbs.pl line 22, <$fh> line 1.
make: *** [golpe/rules.mk:44: build/golpe.h] Error 1
make: *** Waiting for unfinished jobs....
error: /home/ubuntu/strfry/fbs/nostr-index.fbs:4: 16: error: expecting: ] instead got: :
flatc failure at golpe/external/rasgueadb/rasgueadb-generate line 146, <$fh> line 1.
make: *** [golpe/rules.mk:54: build/defaultDb.h] Error 1
```

The steps I took to reproduce are:

- sudo apt install -y git build-essential libyaml-perl libtemplate-perl libregexp-grammars-perl libssl-dev zlib1g-dev liblmdb-dev libflatbuffers-dev libsecp256k1-dev libzstd-dev
- git clone https://github.com/hoytech/strfry.git
- cd strfry/
- git checkout tags/0.9.3
- git submodule update --init
- make setup-golpe
- make -j4

This machine is running Ubuntu 20.04.6 LTS.

Any assistance appreciated!

**Comment by leesalminen** [comment]
I see now that only Ubuntu 22.04+ is supported and I was running 20.04.

**Comment by hoytech** [comment]
Yeah I think you might be able to get this to work by upgrading flatbuffers manually, but it's a bit of a pain. Sorry!
