### ISSUE TITLE
A question regarding the sync command

### ISSUE THREAD

**Issue by 0xtrr** [hoytech/strfry#71]
Hi! I'm planning on moving my relay from nostr-rs-relay to strfry but I'm not sure if I should import events from the old relay db using the sync command or a jsonl file.

> Warning: Syncing can consume a lot of memory and bandwidth if the DBs are highly divergent (for example if your local DB is empty and your filter matches many events).

The current database contains 25.3 million events and the server is currently configured with 64 GB of DDR4 ram. Would that be enough or should I go with a jsonl export/import solution? Is it possible to "guesstimate" this at all?

**Comment by hoytech** [comment]
Hi! The sync command only works for relays that support the negentropy protocol, which AFAIK nostr-rs-relay does not, so you can't use that. In theory you could do this over a websocket connection, but with that number of events, export/import via a jsonl file will be much (much) faster.

In fact, sync isn't really designed for bulk loading many events. It's best for patching relatively small holes in the DB, and/or for clients to sync their local caches with a relay's dataset.

**Comment by 0xtrr** [comment]
Thanks for the quick response @hoytech, I'll stick to the jsonl approach then!
