### ISSUE TITLE
Importing events from another relay using .jsonl import

### ISSUE THREAD

**Issue by Darecjo** [hoytech/strfry#74]
i tried to import a set of data exported from another relay to the deployed relay however none of the event are showing except one or two and im seeing the following results is there any particular format i need to follow exactly ?
![Screenshot 2023-10-05 at 12 00 31 PM](https://github.com/hoytech/strfry/assets/29741039/190f7ae9-b82e-4349-8d88-4f9b83cd9655)

PS: the `.jsonl` file is exported from a nostream-db instance extracted from the postgresql using the following code: 

```
Using psql:
\COPY (
    SELECT row_to_json(t)::text
    FROM (
        SELECT 
            event_content as content,
            event_created_at as created_at,
            encode(event_id, 'hex') as id,
            event_kind as kind,
            encode(event_pubkey, 'hex') as pubkey,
            encode(event_signature, 'hex') as sig,
            event_tags as tags
        FROM events
        WHERE deleted_at is null
    ) t
) TO '/tmp/events.jsonl';
```

**Comment by hoytech** [comment]
Can you paste a few lines from the file? It's probably they are malformed somehow, like maybe a level of quoting, or some leading data, or something like this.

**Comment by Darecjo** [comment]
You're right the file was malformed technically since it is exported the `\` was doubled `\\` due the postgresql exporting function.
![Screenshot 2023-10-28 at 2 09 22 PM](https://github.com/hoytech/strfry/assets/29741039/9e9c4826-aa97-4669-836e-38aaa61f9f9e)

Problem solved thanks.

**Comment by hoytech** [comment]
Ahhh, thanks for letting us know!
