### ISSUE TITLE
Feature: retention period

### ISSUE THREAD

**Issue by kroese** [hoytech/strfry#75]
Because of diskspace constraints I cannot store all incoming messages indefinitely, so it would be very handy if there would be setting that let you specify an amount in days (or even better: a max db size) that automaticly purges any messages older than that.

My current workaround is to automaticly delete the database as soon as it reaches 50 GB, but it would be nicer if it would be "rolling" so that the amount of history available always stays the same.

**Comment by hoytech** [comment]
Neat idea on the max DB size: The tough thing is figuring out a policy on which events to purge.

If you're OK with the time-based policy, you could put `strfry delete --age $MAX_AGE_SECONDS` into a cron-job.

**Comment by hoytech** [comment]
I think this behaviour makes sense: When you delete values from LMDB, it doesn't actually shrink the DB size, it just leaves it as free-space that will get used for subsequent writes.

So I think doing the compact one time is probably sufficient, and the DB size will grow up to the "high water mark" (the largest amount stored at any one given time), and stay there.
